name: Container Build and Release

on:
  workflow_call:
    inputs:
      version:
        description: "Semantic version of the image"
        required: true
        type: string

      container-file:
        description: "Path to the Dockerfile"
        type: string
        default: "Dockerfile"

      container-context:
        description: "Build's context is the set of files located in the specified PATH or URL"
        type: string
        default: "."

      container-name:
        description: "Name of the container"
        type: string
        default: "${{ github.repository }}"

      sbom:
        description: "Generate and upload SBOM"
        type: string
        default: "true"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.container-name }}

jobs:
  publish-image:
    runs-on: ubuntu-latest

    permissions:
      # to upload SBOM
      id-token: write
      contents: write
      packages: write          # to upload Docker image
      attestations: write      # Upload attestations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Container Metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # latest / main
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            # SemVer
            type=semver,pattern={{version}},value=${{ inputs.version }}
            type=semver,pattern=v{{version}},value=${{ inputs.version }}
            type=semver,pattern=v{{major}},value=${{ inputs.version }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ inputs.version }}
    
      - name: Build & Publish Container ${{ env.IMAGE_NAME }}
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        id: build
        with:
          file: "${{ inputs.container-file }}"
          context: "${{ inputs.container-context }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # SBOM Settings
          sbom: true

      # Upload Software Bill of Materials (SBOM) to GitHub
      - name: Upload SBOM
        uses: advanced-security/spdx-dependency-submission-action@169d22427d74f3faf93504e70b03eede8dab272a  # v0.2.0
        with:
          filePath: '.'
          filePattern: '*.spdx.json'

      # Build provenance attestations
      - name: Attest Container Image
        uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f  # v3.2.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      # - name: Attest Container SBOM
      #   uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f  # v3.2.0
      #   with:
      #     subject-path:: '*.spdx.json'
