name: Container Security Scanning

on:
  workflow_call:
    inputs:
      version:
        description: "Semantic version of the image"
        type: string

      container-file:
        description: "Path to the Dockerfile"
        type: string
        default: "Dockerfile"

      container-context:
        description: "Build's context is the set of files located in the specified PATH or URL"
        type: string
        default: "."

      container-name:
        description: "Name of the container"
        type: string
        default: "${{ github.repository }}"

      scanning-block:
        description: "Block the build if vulnerabilities are found"
        type: string
        default: "false"

env:
  REGISTRY: ghcr.io

jobs:
  scan-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build Initial Container
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        id: build
        with:
          file: "${{ inputs.container-file }}"
          context: "${{ inputs.container-context }}"
          load: true
          push: false
          tags: localbuild/testimage:latest

      # Scan the image for vulnerabilities
      - name: Run the Anchore / Grype scan action
        uses: anchore/scan-action@7c05671ae9be166aeb155bad2d7df9121823df32 # v6.1.0
        id: scan
        with:
          image: localbuild/testimage:latest
          only-fixed: true
          fail-build: ${{ inputs.scanning-block }}

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: sarif
          path: ${{ steps.scan.outputs.sarif }}

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
